[package]
name = "image_effects"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.22.1"
image = "0.23.14"
wasm-bindgen = "0.2.83"


[dependencies.web-sys]
version = "0.3.60"
features = ["console"]
